### ISSUE TITLE
SOAP UI tests fail when run against the Resolver Service

### ISSUE THREAD

**Issue by SolidsoftReplyDevelopment** [Solidsoft-Reply/ESB-Libraries#5]
Requests from the resolver are handled correctly by the Resolver Service.  However, when I dump the raw request and replay it via SOAP UI, the tests fail with custom serialisation issues.

**Comment by SolidsoftReplyDevelopment** [comment]
A preliminary investigation suggests that this may be related to a lack of adequate namespace resolution in the current code.  I will investigate further.

**Comment by cnayoung** [comment]
The issue was actually due to problems with serialising Key and Value elements in serialised dictionaries.  The code worked for the XML produced by the resolver but did not adequately take into consideration scenarios where additional whitespace is introduced.  The code has been improved to ensure that it works properly in these situations, and hence makes it much easier to test the Resolution Server using SOAP UI.
